TruckManagementSystem/Controllers/MaintenanceController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using TruckManagementSystem.Helpers;
using TruckManagementSystem.Models;
using TruckManagementSystem.ViewModels;

namespace TruckManagementSystem.Controllers
{
    [Authorize]
    public class MaintenanceController : Controller
    {

        ApplicationDbContext db = new ApplicationDbContext();



        public ActionResult Maintenance()
        {




            return View();
        }

        // GET: Maintenance
        public ActionResult Index(int? page, string searchString, string currentFilter, int?statusid, int?currentFilter1)
        {

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            if (statusid != null)
            {
                page = 1;
            }
            else
            {
                statusid = currentFilter1;
            }

            ViewBag.CurrentFilter1 = statusid;





            int pageSize = 10;
            int pageNumber = (page ?? 1);


            var maintenanceIndex = new List<Maintenance_Book_Header>();
            if (!string.IsNullOrEmpty(searchString) && statusid == null)
            {
                maintenanceIndex = db.Maintenance_Book_Header.Where(x => x.Fleet_No.Contains(searchString) || x.Job_Card_Reference_No.Contains(searchString)).OrderByDescending(x => x.Id).ToList();

            }else if(!string.IsNullOrEmpty(searchString) && statusid != null)
            {
                maintenanceIndex = db.Maintenance_Book_Header.Where(x => (x.Fleet_No.Contains(searchString) || x.Job_Card_Reference_No.Contains(searchString)) && x.Status == statusid).OrderByDescending(x => x.Id).ToList();


            }
            else if (string.IsNullOrEmpty(searchString) && statusid != null)
            {
                maintenanceIndex = db.Maintenance_Book_Header.Where(x =>  x.Status == statusid).OrderByDescending(x => x.Id).ToList();


            }
            else
            {
                maintenanceIndex = db.Maintenance_Book_Header.OrderByDescending(x => x.Created_At).ToList();
            }



            List<SelectListViewModel> StatusList = new List<SelectListViewModel>();


            var intlist = new List<int>()
            {
               Values.STATUS_PENDING,
                Values.STATUS_WAITING_FOR_TRANSPORT_MANAGER,
                Values.STATUS_WAITING_FOR_ACCOUNTANT,             
                Values.STATUS_WAITING_FOR_COUNTRY_MANAGER,
               
            };

            foreach(var item in intlist)
            {

                var item1 = new SelectListViewModel();
                item1.Text = Values.STATUS_STRING(item);
                item1.Value = item.ToString();
                StatusList.Add(item1);

            }


            //      ViewBag.remark = RemarksList.Add(new SelectListViewModel() { Text = "Northern Cape", Value = "NC" });

            ViewBag.Status_Select = StatusList;
            //var item2 = new SelectListViewModel();
            //item2.Text = "No Action";
            //item2.Value = "No Action";

            //RemarksList.Add(item2);

            if (Request.IsAjaxRequest())
            {

                return PartialView("_MaintenanceIndexPartialView", maintenanceIndex.ToPagedList(pageNumber, pageSize));
            }
            return PartialView("_MaintenanceIndexPartialView", maintenanceIndex.ToPagedList(pageNumber, pageSize));


        }


        public ActionResult Create()
        {

            var repairviewmodel = new RepairViewModel();

            repairviewmodel.Created_Date = DateTime.Now.ToString();
            var defaultline = new Repair_Line_Item();
            defaultline.Item = "";
            repairviewmodel.Line_Item = new List<Repair_Line_Item>();


            repairviewmodel.Line_Item.Add(defaultline);
            if (Request.IsAjaxRequest())
            {



                return PartialView("_MaintenanceCreatePartialView", repairviewmodel);
            }
            return View("_MaintenanceCreatePartialView", repairviewmodel);


        }


        public ActionResult GetFleet(string searchstring)
        {

            var fleetlist = db.Fleets.Where(x => x.Fleet_No.Contains(searchstring)).Select(x => new
            {
                label = x.Fleet_No,
                value = x.Id.ToString()
            });



            return Json(fleetlist.Take(15), JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetFleetDetails(int id)
        {

            var fleetobject = db.Fleets.Find(id);






            return Json(fleetobject, JsonRequestBehavior.AllowGet);






        }

        public ActionResult GetStock(string search)
        {
                       
            var location = db.Location.Where(x => x.Name == Values.MAIN_STORE).Select(x => x.Id).FirstOrDefault();

            var stockobj = db.Stock.Where(X => X.Item_Name.Contains(search) || X.Part_Number.Contains(search)).Select(x => new StockLedgerViewModel()

            {

                Stock_Id = x.Stock_Id,
                Item_Name = x.Item_Name,

                Location_Id = x.Location_Id,
                Item_Id = x.Item_Id,
                Qty_Bal = x.Qty_Bal,
                Qty_In = x.Qty_In,
                settled = x.Settled

            });

            var stocklocation = stockobj.Where(l => l.Location_Id == location).ToList();

            var trackerobject = db.Qty_Bal_Tracker.ToList();

            List<int> la = new List<int>();

            foreach (var q in stocklocation.GroupBy(x => x.Item_Id))
            {

                var t = q.Select(x => new { Qty_Bal = x.Qty_Bal }).Last().Qty_Bal;

                var k = q.Select(x => x.Item_Id).LastOrDefault();

                var sum = db.Qty_Bal_Tracker.Where(x => x.Item_Id == k && x.Location_Id == location).ToList().Sum(x => x.Qty_Bal);


                if ((t - sum) <= 0)
                {
                    var p = q.Select(x => x.Item_Id).LastOrDefault();

                    la.Add(p);
                }

            }



            var barItems = stockobj.Where(t => !la.Contains(t.Item_Id) && t.Location_Id == location).ToList();



            var groupedList = new List<Stock>();


            foreach (var item in barItems.GroupBy(x => x.Item_Id))
            {
                var tempstock = new Stock();

                var stockcheck = item.Where(x => x.Qty_In != 0 && x.settled == 0).Select(x => x.Item_Id).FirstOrDefault();
                if (stockcheck != 0)
                {



                    tempstock.Stock_Id = item.Where(x => x.Qty_In != 0 && x.settled == 0).Select(x => x.Stock_Id).FirstOrDefault();
                    tempstock.Item_Id = item.Where(x => x.Qty_In != 0 && x.settled == 0).Select(x => x.Item_Id).FirstOrDefault();
                    tempstock.Item_Name = item.Where(x => x.Qty_In != 0 && x.settled == 0).Select(x => x.Item_Name).FirstOrDefault();


                    groupedList.Add(tempstock);
                }
                else
                {
                    tempstock.Stock_Id = item.Where(x => x.Qty_In != 0 && x.settled == 1).Select(x => x.Stock_Id).LastOrDefault();
                    tempstock.Item_Id = item.Where(x => x.Qty_In != 0 && x.settled == 1).Select(x => x.Item_Id).LastOrDefault();
                    tempstock.Item_Name = item.Where(x => x.Qty_In != 0 && x.settled == 1).Select(x => x.Item_Name).LastOrDefault();




                    groupedList.Add(tempstock);

                }
            }


            var json = string.Empty;

            var result = new List<Dictionary<string, string>>();


            var barItem = new[] { new { label = "", value = "" } }.AsEnumerable();

            var culture = CultureInfo.CurrentCulture;


            barItem = groupedList.Where(x => culture.CompareInfo.IndexOf(x.Item_Name ?? "", search, CompareOptions.IgnoreCase) >= 0).ToList().Select(x => new { label = x.Item_Name, value = x.Item_Id.ToString() + "," + x.Stock_Id.ToString() });


            var excludelist = barItem.Select(x => x.label).ToList();

            var locid = db.Location.Where(x => x.Name == Values.MAIN_STORE).Select(x => x.Id).FirstOrDefault();

            var priceexcluded = db.Price_List.Where(x => (!excludelist.Any(e => x.Item_Name.Contains(e))) && x.Location_Id == locid).ToList();
            //get from pricelist

            var nonstockitems = priceexcluded.Where(x => x.Item_Name.ToLower().Contains(search.ToLower()) || ( !string.IsNullOrEmpty(x.Part_Number) && x.Part_Number.Contains(search))).Select(x => new { label = x.Item_Name, value = x.Item_Id.ToString() + ",P" + x.Id.ToString() });
            //var nonstockitems = db.Price_List.Where(x => x.Item_Name.ToLower().Contains(search.ToLower())).Select(x => new { label = x.Item_Name, value = x.Item_Id.ToString() });

            barItem = barItem.Concat(nonstockitems);

            
            // Join bar items without stock

            //
            var baritem1 = new[] { new { label = "", value = "" } }.AsEnumerable();

     baritem1 = barItem.GroupBy(x => x.label).Select(x => new { x.FirstOrDefault().label, x.FirstOrDefault().value });
            string resultobject = JsonConvert.SerializeObject(result);





            return Json(barItem.Take(15), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetStockDetails(string id)
        {

            string[] stringarr = id.Split(',');
            int itemid = 0;
            int stockid = 0;
            int pricelistid = 0;

TruckManagementSystem/Views/Maintenance/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

TruckManagementSystem/Views/Maintenance/_IssueNoteEdit.cshtml
@model  TruckManagementSystem.ViewModels.IssueNoteViewModel


@using TruckManagementSystem.Helpers


    <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title" style="text-align:center">Issue Note</h4>


            <button type="button" class="close" data-dismiss="modal">&times;</button>


        </div>


        @using (Html.BeginForm("EditIssueNote", "Maintenance", FormMethod.Post,
                                new { id = "jobcardform", enctype = "multipart/form-data" }))
        {

            @Html.HiddenFor(model => model.Id);

            @Html.HiddenFor(model => model.Reference_No);
            <!-- Modal body -->
            <div class="modal-body">

                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">

                            <div class="col-md-4 col-sm-4 col-xs-4">

                                <div class="row" style="margin-bottom:10px">
                                    @Html.Label("Job Number:", htmlAttributes: new { @style = "float:left;margin-right:18px;margin-left:14px;width:44px;" })

                                    <div class="col-md-8">

                                        @Html.EditorFor(model => model.JOBNumber, null, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    </div>

                                </div>


                                <div class=" row">
                                    @Html.Label("Issue Note No:", htmlAttributes: new { @style = "float:left;margin-right:10px;margin-left:14px;width:50px;" })

                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Issue_Note_Number, null, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    </div>
                                </div>


                                <div class=" row">
                                    @Html.Label("Vendor:", htmlAttributes: new { @style = "float:left;margin-right:18px;margin-left:14px;" })

                                    <div class="col-md-8">

                                        @Html.EditorFor(model => model.Vendor_Name, null, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })


                                    </div>
                                </div>



                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4">

                                <h3 style="text-align: center; font-weight: 600 !important; text-transform: uppercase">

                                    Issue Note
                                </h3>




                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <div style="float:left">Date:</div>

                                <div class=" col-sm-8" style="margin-left:65px; margin-bottom:10px">


                                    @Html.EditorFor(model => model.CreatedAt, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @style = "width:165px" } })

                                </div>
                                <div style="float:left">Username: </div>

                                <div class="col-sm-8" style="margin-left: 65px">


                                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @style = "width:165px" } })
                                </div>

                            </div>

                        </div>
                    </div>
                </div>

                <div class="row">
                    <table class="table  table-striped " id="Table1edit">
                        <thead>
                            <tr>
                                <th style="width:40px">ID</th>
                                <th style="width:250px">ITEM</th>
                                <th style="width:150px"> QUANTITY AVAILABLE</th>
                                <th style="width:150px"> QUANTITY REQUESTED</th>
                                <th style="width:150px"> UNIT</th>
                                <th style="width:150px"> UNIT PRICE </th>
                                <th style="width:150px"> SUBTOTAL</th>
                            </tr>

                        </thead>
                        <tbody>

                            @for (int i = 0; i < (Model.IssueNote_Line_Item.Count); i++)
                            {



                                @* @Html.HiddenFor(model => model.LPO_Line_Item[i].Status)*@


                                <tr id="@(i + 1 )">
                                    <td>
                                        @(i + 1)
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.IssueNote_Line_Item[i].Item_Name, new { @class = "form-control input-sm", @placeholder = "Item", @readonly = "readonly" })

                                    </td>
                                    <td>
                                        @Html.HiddenFor(model => model.IssueNote_Line_Item[i].Stock_Id)
                                        @Html.TextBoxFor(model => model.IssueNote_Line_Item[i].Stock_Qty, new { @class = "form-control input-sm", @placeholder = "Quantity", @readonly = "readonly" })

                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.IssueNote_Line_Item[i].quantity, new { @class = "form-control input-sm", @placeholder = "Quantity", @readonly = "readonly" })

                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.IssueNote_Line_Item[i].Unit, new { @class = "form-control input-sm", @placeholder = "Price", @readonly = "readonly" })

                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.IssueNote_Line_Item[i].Price, new { @class = "form-control input-sm", @placeholder = "Price", @readonly = "readonly" })

                                    </td>
                                    <td>
                                        @Html.TextBoxFor(model => model.IssueNote_Line_Item[i].Total, new { @class = "form-control input-sm", @placeholder = "Total", @readonly = "readonly" })

                                    </td>
                                </tr>

                            }


                        </tbody>
                    </table>




                </div>

            </div>


            <div class="modal-footer">

                @if ((User.IsInRole(Values.WORKSHOP_MANAGER_ROLE) || User.IsInRole(Values.ADMIN_ROLE)) && (Model.Status == Values.STATUS_PENDING))
                {




                    <button type="submit" class="btn btn-primary">Approve</button>

                }

            </div>


        }




        }

TruckManagementSystem/Views/Maintenance/_IssueNoteIndexPartialView.cshtml
@model PagedList.IPagedList<TruckManagementSystem.Models.Issue_Note_Header>

@using PagedList.Mvc;


@using (Ajax.BeginForm("IssueNotelist", "Maintenance",

    new AjaxOptions()
    {
        HttpMethod = "POST",

        UpdateTargetId = "result_content"

    }))
{
    <div class="row">


        <div class="input-group mb-3" style="padding-left:70%">
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Search By Job Card No Or Issue No" })
            <div class="input-group-append">
                <button class="btn btn-success" type="submit" style="height:35px">Go</button>
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-body box-danger">

            <div class="table-responsive">
                <table class="table mg-b-0">
                    <thead>
                        <tr>
                            <th>Issue Note No.</th>
                            <th>Job card No.</th>
                            <th> Created Date</th>
                            <th>Created By</th>
                            <th>Vendor</th>
                            <th>Total</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {

                            <tr>
                                <td> @Html.DisplayFor(modelItem => item.Issue_Note_Number)</td>
                                <td>@Html.DisplayFor(modelItem => item.Reference_No)</td>
                                <td> @Html.DisplayFor(modelItem => item.CreatedAt)</td>
                                <td> @Html.DisplayFor(modelItem => item.UserName)</td>
                                <td> @Html.DisplayFor(modelItem => item.Vendor_Name)</td>
                                <td> @Html.DisplayFor(modelItem => item.Order_Total)</td>


                                <td><button class="btn fa fa-pencil fa-2x" value="@item.Id" onclick="javascript: editIssueNote(this, this.value)" style="color:#1b84e7"></button> </td>





                                <td></td>
                            </tr>



                        }


                    </tbody>





                </table>
            </div>

        </div>
    </div>


    @Html.PagedListPager(Model,
page => Url.Action("IssueNotelist", new { page, currentFilter = ViewBag.CurrentFilter }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.Classic,
new AjaxOptions
{
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "Get",
    UpdateTargetId = "result_content"
}))


</div>

TruckManagementSystem/Views/Maintenance/_JobCardCompletedIndexPartialView.cshtml
@model PagedList.IPagedList<TruckManagementSystem.Models.Job_Card_Header>
@using PagedList.Mvc;


@using (Ajax.BeginForm("JobCardCompleted", "Maintenance",

    new AjaxOptions()
    {
        HttpMethod = "POST",

        UpdateTargetId = "result_content"

    }))
{
    <div class="row">


        <div class="input-group mb-3" style="padding-left:70%">
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Search By Job Card No Or Fleet No" })
            <div class="input-group-append">
                <button class="btn btn-success" type="submit" style="height:35px">Go</button>
            </div>
        </div>
    </div>
}



<div class="row">
    <div class="col-md-12">
        <div class="box box-body box-danger">

            <div class="table-responsive">
                <table class="table mg-b-0">
                    <thead>
                        <tr>
                            <th>Ref No.</th>
                            <th>Job Card No</th>
                            <th>Fleet No.</th>
                            <th>Status</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {

                        <tr>
                            <td> @Html.DisplayFor(modelItem => item.Id)</td>
                            <td> @Html.DisplayFor(modelItem => item.Job_Card_Reference_No)</td>
                            <td> @Html.DisplayFor(modelItem => item.Fleet_No)</td>
                            <td> @Html.DisplayFor(modelItem => item.Status_String)</td>


                            <td><button class="btn fa fa-pencil fa-2x" value="@item.Id" onclick="javascript: editJobCard(this, this.value)" style="color:#1b84e7"></button> </td>





                            <td></td>
                        </tr>



                        }


                    </tbody>





                </table>
            </div>

        </div>
    </div>

    @Html.PagedListPager(Model,
page => Url.Action("JobCardCompleted", new { page, currentFilter = ViewBag.CurrentFilter }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.Classic,
new AjaxOptions
{
  InsertionMode = InsertionMode.Replace,
  HttpMethod = "Get",
  UpdateTargetId = "result_content"
}))


</div>

TruckManagementSystem/Views/Maintenance/_JobCardIndexPartialView.cshtml
@model  PagedList.IPagedList<TruckManagementSystem.Models.Job_Card_Header>


@using PagedList.Mvc;

@using (Ajax.BeginForm("JobCardPending", "Maintenance",

    new AjaxOptions()
    {
        HttpMethod = "POST",

        UpdateTargetId = "result_content"

    }))
{
    <div class="row">


        <div class="input-group mb-3" style="padding-left:70%">
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Search By Job Card No Or Fleet No" })
            <div class="input-group-append">
                <button class="btn btn-success" type="submit" style="height:35px">Go</button>
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-body box-danger">



            <div class="table-responsive">
                <table class="table mg-b-0">
                    <thead>
                        <tr>
                            <th>Ref No.</th>
                            <th>Job Card No</th>
                            <th>Fleet No.</th>
                            <th>Status</th>
                            <th>Edit</th>
                           
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {

                        <tr>
                            <td> @Html.DisplayFor(modelItem => item.Id)</td>
                            <td> @Html.DisplayFor(modelItem => item.Job_Card_Reference_No)</td>
                            <td> @Html.DisplayFor(modelItem => item.Fleet_No)</td>
                            <td> @Html.DisplayFor(modelItem => item.Status_String)</td>


                            <td><button class="btn fa fa-pencil fa-2x" value="@item.Id" onclick="javascript: editJobCard(this, this.value)" style="color:#1b84e7"></button> </td>






                        </tr>



                        }


                    </tbody>





                </table>
            </div>

        </div>
    </div>


    @Html.PagedListPager(Model,
page => Url.Action("JobCardPending", new { page, currentFilter = ViewBag.CurrentFilter }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.Classic,
 new AjaxOptions
 {
     InsertionMode = InsertionMode.Replace,
     HttpMethod = "Get",
     UpdateTargetId = "result_content"
 }))



</div>

TruckManagementSystem/Views/Maintenance/_LPOIndexPartialView.cshtml
@model PagedList.IPagedList<TruckManagementSystem.Models.LPO_Header>

@using PagedList.Mvc;


@using (Ajax.BeginForm("LPOlist", "Maintenance",

    new AjaxOptions()
    {
        HttpMethod = "POST",

        UpdateTargetId = "result_content"

    }))
{
    <div class="row">


        <div class="input-group mb-3" style="padding-left:70%">
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Search By Job Card No Or LPO No" })
            <div class="input-group-append">
                <button class="btn btn-success" type="submit" style="height:35px">Go</button>
            </div>
        </div>
    </div>
}


<div class="row">
    <div class="col-md-12">
        <div class="box box-body box-danger">


            <div class="table-responsive">
                <table class="table mg-b-0">
                    <thead>
                        <tr>
                            <th>LPO No.</th>
                            <th>Job Card No.</th>
                            <th> Created Date</th>
                            <th>Created By</th>
                            <th>Vendor</th>
                            <th>Total</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {

                            <tr>
                                <td> @Html.DisplayFor(modelItem => item.LPO_Number)</td>
                                <td> @Html.DisplayFor(modelItem => item.JOBNumber)</td>
                                <td> @Html.DisplayFor(modelItem => item.CreatedAt)</td>
                                <td> @Html.DisplayFor(modelItem => item.UserName)</td>
                                <td> @Html.DisplayFor(modelItem => item.Vendor_Name)</td>
                                <td> @Html.DisplayFor(modelItem => item.Order_Total)</td>


                                <td><button class="btn fa fa-pencil fa-2x" value="@item.Id" onclick="javascript: editLPO(this, this.value)" style="color:#1b84e7"></button> </td>





                                <td></td>
                            </tr>



                        }


                    </tbody>





                </table>
            </div>

        </div>
    </div>


    @Html.PagedListPager(Model,
page => Url.Action("LPOlist", new { page, currentFilter = ViewBag.CurrentFilter }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.Classic,
new AjaxOptions
{
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "Get",
    UpdateTargetId = "result_content"
}))



</div>

TruckManagementSystem/Views/Maintenance/_PaymentsIndexPartialView.cshtml
@model PagedList.IPagedList<TruckManagementSystem.Models.Payment_Header>

@using PagedList.Mvc;

@using (Ajax.BeginForm("Paymentslist", "Maintenance",

    new AjaxOptions()
    {
        HttpMethod = "POST",

        UpdateTargetId = "result_content"

    }))
{
    <div class="row">


        <div class="input-group mb-3" style="padding-left:70%">
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Search By Job Card No Or Payment No" })
            <div class="input-group-append">
                <button class="btn btn-success" type="submit" style="height:35px">Go</button>
            </div>
        </div>
    </div>
}


<div class="row">
    <div class="col-md-12">
        <div class="box box-body box-danger">

            <div class="table-responsive">
                <table class="table mg-b-0">
                    <thead>
                        <tr>
                            <th>Payment No.</th>
                            <th>Job Card No.</th>
                            <th> Created Date</th>
                            <th>Created By</th>
                            <th>Vendor</th>
                            <th>Total</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {

                            <tr>
                                <td> @Html.DisplayFor(modelItem => item.Payment_Number)</td>
                                <td> @Html.DisplayFor(modelItem => item.JOBNumber)</td>
                                <td> @Html.DisplayFor(modelItem => item.CreatedAt)</td>
                                <td> @Html.DisplayFor(modelItem => item.UserName)</td>
                                <td> @Html.DisplayFor(modelItem => item.Vendor_Name)</td>
                                <td> @Html.DisplayFor(modelItem => item.Order_Total)</td>


                                <td><button class="btn fa fa-pencil fa-2x" value="@item.Id" onclick="javascript: editPayment(this, this.value)" style="color:#1b84e7"></button> </td>





                                <td></td>
                            </tr>



                        }


                    </tbody>





                </table>
            </div>
        </div>
    </div>

    @Html.PagedListPager(Model,
page => Url.Action("Paymentslist", new { page, currentFilter = ViewBag.CurrentFilter }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.Classic,
new AjaxOptions
{
   InsertionMode = InsertionMode.Replace,
   HttpMethod = "Get",
   UpdateTargetId = "result_content"
}))

</div>