TruckManagementSystem/Models/Items.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TruckManagementSystem.Helpers;

namespace TruckManagementSystem.Models
{
    public class Items
    {


        [Key]

        public int Item_Id { get; set; }
        public string Item_Name { get; set; }
        public string Description { get; set; }
        [Display(Name = "Created Date")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime? ItemDateCreated { get; set; }
        [Display(Name = "Last Update")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime? ItemDateUpdate { get; set; }
        public int ItemActive { get; set; }
        public int UoM_Id { get; set; }
        public string Barcode { get; set; }
        public string Part_Number { get; set; }
        public int Category { get; set; }
        public int? SubCategory { get; set; }
        public int Taxable { get; set; }
        [Display(Name = "Stock Type")]
        public string Stock_Type { get; set; }

        public string UOM_String
        {
            get
            {
                using ( var db  =  new ApplicationDbContext())
                {

                    var s = db.IC_UoM.Find(UoM_Id);

                    if(s != null)
                    {
                        return s.UoM;

                    }else
                    {
                        return "";
                    }




                }




            }
        }

        public string Stock_Type_Converted
        {
            get
            {
                if(Stock_Type == Values.LOCATION_STOCK.ToString())
                {
                    return "Stock Item";

                }else if(Stock_Type == Values.LOCATION_NON_STOCK.ToString())
                {
                    return "Non Stock Item";
                }else
                {
                    return "";
                }
            }



        }

        public string Vehicle_Type { get; set; }

    }
}

TruckManagementSystem/Controllers/ItemsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TruckManagementSystem.Helpers;
using TruckManagementSystem.Models;
using TruckManagementSystem.ViewModels;

namespace TruckManagementSystem.Controllers
{
    [Securities.RolesAuthorization(Roles = Values.ADMIN_ROLE)]

    public class ItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Items
        public ActionResult Index(int? page, string searchString, string currentFilter)
        {


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            int pageSize = 20;
            int pageNumber = (page ?? 1);

            var items = new List<Items>();
            if (searchString != null)
            {
                items = db.Items.Where(x => x.Item_Name.Contains(searchString) || x.Part_Number.Contains(searchString)).ToList();

            }
            else
            {
                items = db.Items.ToList();
            }

            return View(items.OrderByDescending(x => x.Item_Id).ToList().ToPagedList(pageNumber, pageSize));


            
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Items items = db.Items.Find(id);
            if (items == null)
            {
                return HttpNotFound();
            }
            return View(items);
        }

        // GET: Items/Create
        public ActionResult Create()
        {

            List<SelectListViewModel> RemarksList = new List<SelectListViewModel>();

            //      ViewBag.remark = RemarksList.Add(new SelectListViewModel() { Text = "Northern Cape", Value = "NC" });
            var item1 = new SelectListViewModel();
            item1.Text = "SCANIA";
            item1.Value = "SCANIA";
            RemarksList.Add(item1);

            var item2 = new SelectListViewModel();
            item2.Text = "IVECO";
            item2.Value = "IVECO";

            RemarksList.Add(item2);


            ViewBag.UoM_Id = new SelectList(db.IC_UoM, "UoM_Id", "UoM");


           
            var l = db.Categories.Where(x => x.Name == Values.DEFAULT_CATEGORY).Select(x => x.Id).FirstOrDefault();


            ViewBag.Category = new SelectList(db.Categories, "Id", "Name", l);



            ViewBag.Vehicle = RemarksList;


            var selectlistitems = new List<SelectListItem>()
    {
        new SelectListItem() {Text="Stock Item", Value= Values.LOCATION_STOCK.ToString()},
        new SelectListItem() { Text="Non Stock Item", Value= Values.LOCATION_NON_STOCK.ToString()}};

            ViewBag.Stock_Type = new SelectList(selectlistitems, "Value", "Text", Values.LOCATION_STOCK.ToString());

            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Item_Id,Item_Name,Description,ItemDateCreated,ItemDateUpdate,ItemActive,UoM_Id,Barcode,Part_Number,Vehicle_Type,Category,SubCategory,Taxable,Stock_Type")] Items items)
        {
            //if (ModelState.IsValid)
            //{

            items.Item_Name = items.Item_Name + " " + items.Vehicle_Type;
                items.ItemActive = 1;
           
                items.Taxable = 1; 
                items.Stock_Type =  Convert.ToString(items.Stock_Type);

                db.Items.Add(items);
                db.SaveChanges();
                return RedirectToAction("Index");
       //     }

      //      return View(items);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Items items = db.Items.Find(id);
            if (items == null)
            {
                return HttpNotFound();
            }




            List<SelectListViewModel> RemarksList = new List<SelectListViewModel>();

            //      ViewBag.remark = RemarksList.Add(new SelectListViewModel() { Text = "Northern Cape", Value = "NC" });
            var item1 = new SelectListViewModel();
            item1.Text = "SCANIA";
            item1.Value = "SCANIA";
            RemarksList.Add(item1);

            var item2 = new SelectListViewModel();
            item2.Text = "IVECO";
            item2.Value = "IVECO";

            RemarksList.Add(item2);

            ViewBag.Vehicle = RemarksList;


            ViewBag.UoM_Id = new SelectList(db.IC_UoM, "UoM_Id", "UoM",items.UoM_Id);


            var l = db.Categories.Where(x => x.Name == Values.DEFAULT_CATEGORY).Select(x => x.Id).FirstOrDefault();


            ViewBag.Category = new SelectList(db.Categories, "Id", "Name", items.Category);



            var selectlistitems = new List<SelectListItem>()
    {
        new SelectListItem() {Text="Stock Item", Value= Values.LOCATION_STOCK.ToString()},
        new SelectListItem() { Text="Non Stock Item", Value= Values.LOCATION_NON_STOCK.ToString()}};

            ViewBag.Stock_Type = new SelectList(selectlistitems, "Value", "Text", Values.LOCATION_STOCK);




            return View(items);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Item_Id,Item_Name,Description,ItemDateCreated,ItemDateUpdate,ItemActive,UoM_Id,Barcode,Part_Number,Category,SubCategory,Taxable,Stock_Type, Vehicle_Type")] Items items)
        {
            if (ModelState.IsValid)
            {
             
                    items.Item_Name = items.Item_Name + " " + items.Vehicle_Type;


                items.Item_Name = items.Item_Name.Trim();
                
               
                db.Entry(items).State = EntityState.Modified;
                db.SaveChanges();

                var priceobject = db.Price_List.Where(x => x.Item_Id == items.Item_Id).ToList();

                foreach(var item in priceobject)
                {

                    item.Item_Name = items.Item_Name;
                    item.Part_Number = items.Part_Number;

                    db.Entry(items).State = EntityState.Modified;
                }

                var stockobj = db.Stock.Where(x => x.Item_Id == items.Item_Id).ToList();

                foreach(var stck in stockobj)
                {

                    stck.Item_Name = items.Item_Name;
                    stck.Part_Number = items.Part_Number;

                    db.Entry(stck).State = EntityState.Modified;
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(items);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Items items = db.Items.Find(id);
            if (items == null)
            {
                return HttpNotFound();
            }
            return View(items);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Items items = db.Items.Find(id);
            db.Items.Remove(items);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TruckManagementSystem/Views/Items/Create.cshtml
@model TruckManagementSystem.Models.Items

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Items</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Item_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Item_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Item_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Vehicle_Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Vehicle_Type, new SelectList(ViewBag.Vehicle, "Text", "Value"), "Select", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Vehicle_Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Part_Number, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Part_Number, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Part_Number, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UoM_Id, "Unit", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UoM_Id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UoM_Id, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Category, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Category", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UoM_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Stock_Type, "Stock Type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Stock_Type", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Stock_Type, "", new { @class = "text-danger" })
        </div>
    </div>





    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TruckManagementSystem/Views/Items/Delete.cshtml
@model TruckManagementSystem.Models.Items

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Items</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Item_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item_Name)
        </dd>

  
  
        <dt>
            @Html.DisplayNameFor(model => model.UoM_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UOM_String)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Part_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Part_Number)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Vehicle_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vehicle_Type)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Stock_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stock_Type)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TruckManagementSystem/Views/Items/Details.cshtml
@model TruckManagementSystem.Models.Items

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Items</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Item_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemDateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemDateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemDateUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemDateUpdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UoM_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UoM_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Barcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Barcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemReference)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemReference)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubCategory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubCategory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Taxable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Taxable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stock_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stock_Type)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Item_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TruckManagementSystem/Views/Items/Edit.cshtml
@model TruckManagementSystem.Models.Items

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Items</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Item_Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Item_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Item_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Item_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Vehicle_Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Vehicle_Type, new SelectList(ViewBag.Vehicle, "Text", "Value", Model.Vehicle_Type), "Select", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Vehicle_Type, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Part_Number, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Part_Number, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Part_Number, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.UoM_Id, "UoM_Id", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UoM_Id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UoM_Id, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Category, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Category", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UoM_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Stock_Type, "Stock Type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Stock_Type", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Stock_Type, "", new { @class = "text-danger" })
        </div>
    </div>




    @Html.HiddenFor(model => model.Stock_Type)


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TruckManagementSystem/Views/Items/Index.cshtml
@model PagedList.IPagedList<TruckManagementSystem.Models.Items>


@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


@using (Html.BeginForm("Index", "Items", FormMethod.Get))
{
    <div class="row">


        <div class="input-group mb-3" style="padding-left:70%">
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Search By Item Name Or Part Number" })
            <div class="input-group-append">
                <button class="btn btn-success" type="submit" style="height:35px">Go</button>
            </div>
        </div>
    </div>
}


<div class="row">
    <div class="col-md-12">
        <div class="box box-body box-danger">

            <table class="table">
                <tr>
                    <th>
                        Item Name
                    </th>
                    <th>
                        Unit Of Measure
                    </th>
                    <th>
                        Stock Type
                    </th>
                    <th>
                        Part Number
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Item_Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UOM_String)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Stock_Type_Converted)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Part_Number)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Item_Id }) |
                            @*@Html.ActionLink("Details", "Details", new { id=item.Item_Id }) |*@
                            @Html.ActionLink("Delete", "Delete", new { id = item.Item_Id })
                        </td>
                    </tr>
                }

            </table>

        </div>
    </div>


    <br />
    <p>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    </p>
    <br />
    <div class="row">

        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))


    </div>
</div>