TruckManagementSystem/Controllers/TripSheetController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using TruckManagementSystem.Helpers;
using TruckManagementSystem.Models;
using TruckManagementSystem.ViewModels;

namespace TruckManagementSystem.Controllers
{
    public class TripSheetController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: TripSheet
        public ActionResult Index()
        {

        
            return View();
        }

        public ActionResult TripListIndex()
        {

            var triplist = db.Trip_List_Header.ToList();

            return View(triplist);
        }

        public ActionResult TripListCreate()
        {

            var tlvm = new TripListViewModel();


            var defaultline = new Trip_Line_Item();
            defaultline.Fleet_No = "";           

            tlvm.TripLineItems = new List<Trip_Line_Item>();
            tlvm.Transit_Type = db.Transit_Type.Where(x => x.Name.Trim() == "Local").Select(x => x.Id).FirstOrDefault();

            tlvm.TripLineItems.Add(defaultline);

            var categoryid = db.Categories.Where(x => x.Name == Values.PRODUCTS_CATEGORY).Select(x => x.Id).FirstOrDefault();
            ViewBag.Products = db.Items.Where(x => x.Category == categoryid).ToList();

            return PartialView("_TripListCreate", tlvm);

        }

        [HttpPost]
        public ActionResult TripListCreateLocal(TripListViewModel model)
        {

            if (ModelState.IsValid)
            {
                    var triplistheader = new Trip_List_Header();

                triplistheader.Created_Date = DateTime.Now;
                triplistheader.Created_By = System.Web.HttpContext.Current.User.Identity.Name;
                triplistheader.Transit_Type = model.Transit_Type;
         

                db.Trip_List_Header.Add(triplistheader);

                db.SaveChanges();

                var details = new List<Trip_List_Details>();
                
                    foreach(var item in model.TripLineItems)
                {
                    var detail = new Trip_List_Details();

                    detail.Destination = item.Destination;
                    detail.Driver_Name = item.Driver_Name;
                    detail.Fleet_No = item.Fleet_No;
                    detail.Licence_No = item.Licence_No;
                    detail.Mobile_No = item.Mobile_No;
                    detail.Loading_Point = item.Loading_Point;
                    detail.Product = item.Product;
                    detail.Requested_Qty = item.Requested_Qty;
                    detail.Truck_Head = item.Truck_Head;
                    detail.Truck_Trailer = item.Truck_Trailer;
                    detail.Unit = "Ltr";
                    detail.Trip_List_header_Id = triplistheader.Id;
                    detail.Loading_Point = item.Loading_Point;

                    details.Add(detail);


                }

                db.Trip_List_Details.AddRange(details);
                db.SaveChanges();

              

                return RedirectToAction("Index");
            }

         
            return PartialView("_TripListCreate", model);
        }

        public ActionResult LoadingListDetails(int id)
        {

            var loadingdetails = db.Trip_List_Details.Where(x => x.Id == id).ToList();


            return View(loadingdetails);
        }

        public ActionResult LoadingListVehicleDetails(int id)
        {

            var vehicledetails = db.Trip_List_Details.Find(id);




            return View(vehicledetails);
        }

        public ActionResult NewDepartureDetails(int id)
        {

            var tripdetails = new Trip_Details();

            tripdetails.List_Detail_Id = id;

            ViewBag.Unit = new SelectList(db.IC_UoM.ToList(), "UoM_Id", "UoM");

            return PartialView("_NewDepartureDetails", tripdetails);

        }

        [HttpPost]
        public ActionResult NewDepartureDetails(Trip_Details model)
        {
            
            if(ModelState.IsValid)
            {
                var detail = db.Trip_List_Details.Find(model.List_Detail_Id);

                detail.Order_No = model.Order_No;

                db.Entry(detail).State = System.Data.Entity.EntityState.Modified;


                model.Trip_Status = "Departure";
                model.Created_At = DateTime.Now;
                model.Username = System.Web.HttpContext.Current.User.Identity.Name;
                model.Status = Values.STATUS_PENDING;

                db.Trip_Details.Add(model);
                db.SaveChanges();

               
                return RedirectToAction("LoadingListVehicleDetails", new { id = model.List_Detail_Id });

            }

            return PartialView("_NewDepartureDetails", model);

        }


        public ActionResult LoadingInfo(int id)
        {
            var list = db.Trip_Details.Where(x => x.List_Detail_Id == id && x.Trip_Status == "Departure").ToList();


            return PartialView("_LoadingListPartialView", list);
        }

        public ActionResult NewDeliveryDetails(int id)
        {


            var tripdetails = new Trip_Details();

            var detail = db.Trip_List_Details.Find(id);

            tripdetails.List_Detail_Id = id;
            tripdetails.Order_No = detail.Order_No;

            ViewBag.Unit = new SelectList(db.IC_UoM.ToList(), "UoM_Id", "UoM", tripdetails.Unit);


            return PartialView("_NewDeliveryDetails", tripdetails);

        }

        [HttpPost]
        public ActionResult NewDeliveryDetails(Trip_Details model)
        {

            if (ModelState.IsValid)
            {
                model.Trip_Status = "Delivery";
                model.Created_At = DateTime.Now;
                model.Username = System.Web.HttpContext.Current.User.Identity.Name;
                model.Status = Values.STATUS_PENDING;

                db.Trip_Details.Add(model);
                db.SaveChanges();


                return RedirectToAction("LoadingListVehicleDetails", new { id = model.List_Detail_Id });

            }

            return PartialView("_NewDepartureDetails", model);

        }

        public ActionResult DeliveryInfo(int id)
        {
            var list = db.Trip_Details.Where(x => x.List_Detail_Id == id && x.Trip_Status =="Delivery").ToList();


            return PartialView("_DeliveryListPartialView", list);
        }

        public ActionResult CreateTripExpenseVoucher(int id)
        {

            var model = new PaymentViewModel();

            model.Trip_List_detail_Id = id;
            var detail = db.Trip_List_Details.Find(id);

            model.Order_no = detail.Order_No;
            model.Currency = "TZS";


            model.Payment_Line_Item = new List<Payment_Line_Item>();
            var paymentlineitem = new Payment_Line_Item();

            paymentlineitem.Item_Id = db.Items.Where(x => x.Item_Name.Trim() == "ACCOMODATION").Select(x => x.Item_Id).FirstOrDefault();
            paymentlineitem.Item_Name = "ACCOMODATION";
            paymentlineitem.Price = 40000;
            paymentlineitem.quantity = 1;
            paymentlineitem.Unit = "Pc";
            paymentlineitem.Currency = "TZS";
            paymentlineitem.Total = paymentlineitem.Price * paymentlineitem.quantity;

            model.Payment_Line_Item.Add(paymentlineitem);

            paymentlineitem = new Payment_Line_Item();

            paymentlineitem.Item_Id = db.Items.Where(x => x.Item_Name.Trim() == "DRINKING WATER").Select(x => x.Item_Id).FirstOrDefault();
            paymentlineitem.Item_Name = "DRINKING WATER";
            paymentlineitem.Price = 5000;
            paymentlineitem.quantity = 1;
            paymentlineitem.Unit = "Pc";
            paymentlineitem.Currency = "TZS";
            paymentlineitem.Total = paymentlineitem.Price * paymentlineitem.quantity;
            model.Payment_Line_Item.Add(paymentlineitem);

            paymentlineitem = new Payment_Line_Item();
            paymentlineitem.Item_Id = db.Items.Where(x => x.Item_Name.Trim() == "REPLENISHMENT").Select(x => x.Item_Id).FirstOrDefault();

            paymentlineitem.Item_Name = "REPLENISHMENT";
            paymentlineitem.Price = 25000;
            paymentlineitem.quantity = 1;
            paymentlineitem.Unit = "Pc";
            paymentlineitem.Currency = "TZS";
            paymentlineitem.Total = paymentlineitem.Price * paymentlineitem.quantity;
            model.Payment_Line_Item.Add(paymentlineitem);

            paymentlineitem = new Payment_Line_Item();
            paymentlineitem.Item_Id = db.Items.Where(x => x.Item_Name.Trim() == "AIRTIME FOR COMMUNICATING").Select(x => x.Item_Id).FirstOrDefault();
            paymentlineitem.Item_Name = "AIRTIME FOR COMMUNICATING";
            paymentlineitem.Price = 5000;
            paymentlineitem.quantity = 1;
            paymentlineitem.Unit = "Pc";
            paymentlineitem.Currency = "TZS";
            paymentlineitem.Total = paymentlineitem.Price * paymentlineitem.quantity;
            model.Payment_Line_Item.Add(paymentlineitem);

            paymentlineitem = new Payment_Line_Item();
            paymentlineitem.Item_Id = db.Items.Where(x => x.Item_Name.Trim() == "MINOR REPAIR AND OTHER EXPENSES").Select(x => x.Item_Id).FirstOrDefault();
            paymentlineitem.Item_Name = "MINOR REPAIR AND OTHER EXPENSES";
            paymentlineitem.Price = 25000;
            paymentlineitem.quantity = 1;
            paymentlineitem.Unit = "Pc";
            paymentlineitem.Currency = "TZS";
            paymentlineitem.Total = paymentlineitem.Price * paymentlineitem.quantity;
            model.Payment_Line_Item.Add(paymentlineitem);

            paymentlineitem = new Payment_Line_Item();

TruckManagementSystem/Views/TripSheet/Index.cshtml
@model IEnumerable<TruckManagementSystem.Models.Trip_List_Header>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="row simple">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <div class="list-group">
            <a class="list-group-item" href="@Url.Action("TripListIndex", "TripSheet")"> <i class="fa fa-clock-o fa-2x"></i>Loading List</a>
        </div>
    </div>


    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <div class="list-group">
            <a class="list-group-item" href="@Url.Action("TripListCreate", "TripSheet")" id="createtriplist"> <i class="fa fa-hdd-o fa-2x"></i>Create Loading List</a>
        </div>
    </div>
</div>


<div id='myModal' class='modal hide fade in'>
    <div class="modal-dialog  modal-lg" id="tripcreate" style="min-width:1100px">

    </div>
</div>



<script>

     $("#createtriplist").click(function (e) {

        e.preventDefault();

        $.ajax({
            type: 'GET',
            url: '@Url.Content("~/TripSheet/TripListCreate")',

            success: function (result) {
                $('#tripcreate').html(result);

                   $('#myModal').modal('show');
            }
        });



    });



</script>


@section Scripts {

    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>

}

TruckManagementSystem/Views/TripSheet/LoadingListVehicleDetails.cshtml
@model TruckManagementSystem.Models.Trip_List_Details
@{
    ViewBag.Title = "LoadingListVehicleDetails";
}



@Html.HiddenFor(model => model.Id,  new { @id = "hiddendetailid"  })
    <div class="row" style="margin-top:20px">
      

        <div class="dropdown">
            <button class="btn btn-primary  dropdown-toggle"  data-toggle="dropdown" style="margin-left:80px;">
                Create Cash Voucher
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#" id="tripexpensevoucher">Create Local trip Voucher</a>
                <a class="dropdown-item" href="#"id="tripreturnvoucher">Create Transit Return Voucher</a>
               
            </div>
        </div>

        <button class="btn btn-primary" id="newFuelVoucher" style="margin-left:50px;">
            Create Fuel Voucher
        </button>

        <button class="btn btn-primary" id="NewDepartureDetails" style="margin-left:50px;">
            Create Departure Details
        </button>

        <button class="btn btn-primary" id="NewDeliveryDetails" style="margin-left:50px;">
            Create Delivery Details
        </button>
    </div>

    <div class="row col-md-10 offset-md-2" style="margin-top:20px;margin-bottom:20px; background-color:white;width:80%">

        <div class="col-md-6">
            <div class="form-row">
                <label class="col-md-3">
                    <strong>Fleet No:</strong>
                </label>
                <div class="col-sm-8">

                    @Html.DisplayFor(model => model.Fleet_No)
                </div>

            </div>
        </div>
        <div class="col-md-6">
            <div class="form-row">
                <label class="col-md-3">
                    <strong>Truck No:</strong>
                </label>
                <div class="col-sm-8">

                    @Html.DisplayFor(model => model.Truck_Head)
                </div>

            </div>

        </div>
        <div class="col-md-6">
            <div class="form-row">
                <label class="col-md-3">
                    <strong>Trailer No:</strong>
                </label>
                <div class="col-sm-8">

                    @Html.DisplayFor(model => model.Truck_Head)
                </div>

            </div>
        </div>

        <div class="col-md-6">
            <div class="form-row">
                <label class="col-md-3">
                    <strong>Driver No:</strong>
                </label>
                <div class="col-sm-8">

                    @Html.DisplayFor(model => model.Driver_Name)
                </div>

            </div>
        </div>

        <div class="col-md-6">
            <div class="form-row">
                <label class="col-md-3">
                    <strong>Order No:</strong>
                </label>
                <div class="col-sm-8">

                    @Html.DisplayFor(model => model.Order_No)
                </div>

            </div>
        </div>


    </div>


        <div class="row col-md-12">
            <div class="col-md-2">
                <ul>
                    <li>
                        <a id="loadinginfo"><i class="fa fa-fw fa-list-alt"></i>Loading Info</a>
                    </li>

                    <li>
                        <a id="deliveryinfo"><i class="fa fa-fw fa-list-alt"></i>Delivery Info</a>
                    </li>

                    <li>
                        <a id="tripexpensevoucherslist"><i class="fa fa-fw fa-list-alt"></i>Trip Expense Vouchers</a>
                    </li>

                    <li>
                        <a id="fuelexpensevouchers"><i class="fa fa-fw fa-list-alt"></i>Fuel Expense Voucher</a>
                    </li>



                </ul>



            </div>




            <div class="col-md-10" style="background-color:white" id="result_content">




                @Html.Action("LoadingInfo", "TripSheet", new { id = Model.Id })

            </div>

        </div>



        <div id='myModal' class='modal hide fade in'>
            <div class="modal-dialog modal-lg" id="newDetailsCreate" style="width:900px">

            </div>
        </div>

        <div id='myModalEdit' class='modal hide fade in'>
            <div class="modal-dialog  modal-lg" id="maitenanceEdit" style="min-width:1100px">

            </div>
        </div>

        <div id='myModalcreateLPO' class='modal hide fade in'>
            <div class="modal-dialog modal-lg" id="maitenanceCreateLPO" style="min-width:900px">

            </div>
        </div>

        <div id='myModalIssueNote' class='modal hide fade in'>
            <div class="modal-dialog modal-lg" id="maitenanceCreateIssueNote" style="min-width:900px">

            </div>
        </div>
        <script>




             $("#newFuelVoucher").click(function (e) {

        e.preventDefault();

        $.ajax({
            type: 'GET',
            url: '@Url.Content("~/TripSheet/NewFuelVoucher")',
            data: { id: $('#hiddendetailid').val() },
            success: function (result) {

                $('#newDetailsCreate').html(result);

               $('#myModal').modal('show');
            }
        });



    });





    $("#NewDepartureDetails").click(function (e) {

        e.preventDefault();

        $.ajax({
            type: 'GET',
            url: '@Url.Content("~/TripSheet/NewDepartureDetails")',
            data: { id: $('#hiddendetailid').val() },
            success: function (result) {

                $('#newDetailsCreate').html(result);

               $('#myModal').modal('show');
            }
        });



    });



       $("#NewDeliveryDetails").click(function (e) {

        e.preventDefault();

        $.ajax({
            type: 'GET',
            url: '@Url.Content("~/TripSheet/NewDeliveryDetails")',
            data: { id: $('#hiddendetailid').val() },
            success: function (result) {

                $('#newDetailsCreate').html(result);

               $('#myModal').modal('show');
            }
        });



    });


      $("#tripexpensevoucher").click(function (e) {

        e.preventDefault();

        $.ajax({
            type: 'GET',
            url: '@Url.Content("~/TripSheet/CreateTripExpenseVoucher")',
            data: { id: $('#hiddendetailid').val() },
            success: function (result) {

                $('#newDetailsCreate').html(result);

               $('#myModal').modal('show');
            }
        });



      });

     $("#tripreturnvoucher").click(function (e) {

        e.preventDefault();

        $.ajax({
            type: 'GET',
            url: '@Url.Content("~/TripSheet/CreateTransitReturnVoucher")',
            data: { id: $('#hiddendetailid').val() },
            success: function (result) {

                $('#newDetailsCreate').html(result);

               $('#myModal').modal('show');
            }
        });



    });



     $("#loadinginfo").click(function (e) {

        e.preventDefault();

        $.ajax({
            type: 'GET',
            url: '@Url.Content("~/TripSheet/LoadingInfo")',
             data: { id: $('#hiddendetailid').val() },
            success: function (result) {
                $('#result_content').html(result);
            }
        });



     });

    $("#tripexpensevoucherslist").click(function (e) {

        e.preventDefault();

        $.ajax({
            type: 'GET',
            url: '@Url.Content("~/TripSheet/LoadingInfo")',
             data: { id: $('#hiddendetailid').val() },
            success: function (result) {
                $('#result_content').html(result);
            }
        });



     });


     $("#deliveryinfo").click(function (e) {

        e.preventDefault();

        $.ajax({
            type: 'GET',
            url: '@Url.Content("~/TripSheet/DeliveryInfo")',
             data: { id: $('#hiddendetailid').val() },
            success: function (result) {
                $('#result_content').html(result);
            }
        });



    });




    $("#fuelexpensevouchers").click(function (e) {

        e.preventDefault();

        $.ajax({
            type: 'GET',
            url: '@Url.Content("~/TripSheet/FuelInfo")',
               data: { id: $('#hiddendetailid').val() },
          
            success: function (result) {
                $('#result_content').html(result);
            }
        });



    });



     $("#CashPayments").click(function (e) {

        e.preventDefault();

        $.ajax({
            type: 'GET',
            url: '@Url.Content("~/Maintenance/Paymentslist")',

            success: function (result) {
                $('#result_content').html(result);
            }
        });



    });





     $("#newRepairs").click(function (e) {

        e.preventDefault();

        $.ajax({
            type: 'GET',
            url: '@Url.Content("~/Maintenance/Create")',

            success: function (result) {
                $('#maitenanceCreate').html(result);

                $('#myModal').modal('show');




            }
        });



    });

        function editRepairs(obj, value) {

            var idparam = value;

              $.ajax({
            type: 'GET',
            url: '@Url.Content("~/Maintenance/Edit")',
            data: { "idparam":  idparam},

            success: function (result) {
                $('#maitenanceEdit').html(result);

                $('#myModalEdit').modal('show');




            }
        });


        }


      function editJobCard(obj, value) {

            var idparam = value;

              $.ajax({
            type: 'GET',
            url: '@Url.Content("~/Maintenance/EditJobCard")',
            data: { "idparam":  idparam},

            success: function (result) {
                $('#maitenanceEdit').html(result);

                $('#myModalEdit').modal('show');




            }
        });


        }


      function editLPO(obj, value) {

            var idparam = value;

              $.ajax({
            type: 'GET',
            url: '@Url.Content("~/Maintenance/EditLPO")',
            data: { "idparam":  idparam},

            success: function (result) {
                $('#maitenanceEdit').html(result);

                $('#myModalEdit').modal('show');
            }
        });


        }


      function editPayment(obj, value) {

            var idparam = value;

              $.ajax({
            type: 'GET',
            url: '@Url.Content("~/Maintenance/editPayment")',
            data: { "idparam":  idparam},

            success: function (result) {
                $('#maitenanceEdit').html(result);

                $('#myModalEdit').modal('show');




            }
        });


        }

          function editIssueNote(obj, value) {

            var idparam = value;

              $.ajax({
            type: 'GET',
            url: '@Url.Content("~/Maintenance/EditIssueNote")',
            data: { "idparam":  idparam},

            success: function (result) {
                $('#maitenanceCreateIssueNote').html(result);

                $('#myModalIssueNote').modal('show');




            }
        });


        }


       $("#editRepairs").click(function (e) {

           e.preventDefault();

           var idparam = $('#editRepairs').val();








    });

      function createLPO(object, detailId) {

        debugger
      //    var suffix = detailId.match(/\d+/)

         var url = '@Url.Action("CreateLPO", "Maintenance")';


                $.ajax({
                    url: url, type: "GET",
                    data: { "rowid": detailId },

                    success: function (result) {
                        // var a = $.parseJSON(data);
    debugger
                            $('#maitenanceCreateLPO').html(result);

                $('#myModalcreateLPO').modal('show');



                    }
                });



    }

    $(function() {
    $('#myPager').on('click', 'a', function() {
        $.ajax({
            url: this.href,
            type: 'GET',
            cache: false,
            success: function(result) {
                $('#result_content').html(result);
            }
        });
        return false;
    });
});

        </script>

        <style>

            ul {
                list-style-type: none;
                margin: 0px;
                padding: 0px;
            }

                ul > li {
                    margin: 5px;
                }
        </style>

        @section Scripts {

            <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>

        }

TruckManagementSystem/Views/TripSheet/_CreateTransitReturnVoucher.cshtml
@model  TruckManagementSystem.ViewModels.PaymentViewModel



@using (Html.BeginForm("CreateTransitReturnVoucher", "TripSheet", FormMethod.Post,
                 new { id = "departuredetailsform", enctype = "multipart/form-data" }))
{



    <style>
        .modal-body {
            font-size: 12px;
        }

        .table thead > tr > th {
            font-size: 11px;
        }

        .table td {
            padding: 0.3em;
        }


        .form-control, .dataTables_filter input {
            font-size: 12px;
        }
    </style>
    <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title" style="text-align:center">Create Transit Return Voucher</h4>


            <button type="button" class="close" data-dismiss="modal">&times;</button>


        </div>



        @Html.HiddenFor(model => model.Trip_List_detail_Id)
        <div class="modal-body">





            <div class="row">
                <div class="col-md-6 mr-auto" style="margin-bottom:20px">
                    <div class="row">
                        <label class="col-sm-3" style="padding-top:8px">
                            <strong>Order No:</strong>
                        </label>
                        <div class="col-sm-8">
                            @Html.EditorFor(model => model.Order_no, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.Payment_Number, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>
                <table class="table  table-striped " id="Table1create">
                    <thead>
                        <tr>
                            <th style="width:350px">Item Name</th>
                            <th>quantity</th>
                            <th>Price</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>

                        @Html.HiddenFor(model => model.Currency)
                        @Html.HiddenFor(model => model.Order_Total)

                        @for (int i = 0; i < (Model.Payment_Line_Item.Count); i++)
                        {

                            @Html.HiddenFor(model => model.Payment_Line_Item[i].Unit)

                            @Html.HiddenFor(model => model.Payment_Line_Item[i].Currency)
                            <tr>
                                <td>  @Html.EditorFor(model => model.Payment_Line_Item[i].Item_Name, new { htmlAttributes = new { @class = "form-control" } })</td>
                                <td>  @Html.EditorFor(model => model.Payment_Line_Item[i].quantity, new { htmlAttributes = new { @class = "form-control", @type = "number" } })</td>
                                <td>  @Html.EditorFor(model => model.Payment_Line_Item[i].Price, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0", @step = "0.01" } })</td>
                                <td>  @Html.EditorFor(model => model.Payment_Line_Item[i].Total, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0", @step = "0.01" } })</td>

                            </tr>


                        }

                        <tr>
                            <td></td>
                            <td></td>
                            <td>Total</td>
                            <td>@Html.Raw(Model.Order_Total)</td>

                        </tr>


                    </tbody>
                </table>




            </div>


            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" id="savenewdeparturedetails">Create</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>


        </div>


    </div>



}
<table class="sample" style="display:none">

    <tr>
        <td>
        </td>
        <td>

            @Html.TextBox("Fleet_No", null, new { @class = "form-control input-sm", @placeholder = "" })



        </td>
        <td>


            @Html.TextBox("Truck_No", null, new { @class = "form-control" })

        </td>

        <td>
            @Html.TextBox("Truck_No", null, new { @class = "form-control" })
        </td>
        <td>
            @Html.TextBox("Truck_No", null, new { @class = "form-control" })

        </td>
        <td>
            @Html.TextBox("Truck_No", null, new { @class = "form-control" })
        </td>
        <td>
            @Html.TextBox("Truck_No", null, new { @class = "form-control" })
        </td>
        <td>
            @Html.TextBox("Truck_No", null, new { @class = "form-control", })

        </td>
        <td>
            @Html.TextBox("Truck_No", null, new { @class = "form-control", })
        </td>
        <td>
            @Html.TextBox("Truck_No", null, new { @class = "form-control", })

        </td>
        <td>
            @Html.TextBox("Truck_No", null, new { @class = "form-control", })

        </td>
        <td>

            <a href="#" class="fa fa-trash fa-2x" onclick="removeItem(this)"></a>
        </td>


    </tr>

</table>

<script>


    $(document).ready(function () {




        $("#Table1create").on("click", "#addBtncreate", function () {



            var currentrowid = parseInt($('#Table1create tr:last').prev().attr('id'));


            //     $("#Table1create .qtyselected").each(function () {

            //         $(this).prop('readonly', true);


            //});


            currentrowid++;

            var row = jQuery('.sample tr').clone(true);

            row.find("input:text").val("");

            //row.find("td:eq(0) .stockidclass").attr('name', 'Line_Item[' + (currentrowid - 1) + '].');
            // row.find("td:eq(0) .stockidclass").attr('id', 'Line_Item_' + (currentrowid - 1) +'__Stock_Id');

            row.find("td:eq(1) input").attr('name', 'Line_Item[' + (currentrowid - 1) + '].Fleet_No');
            row.find("td:eq(2) input").attr('name', 'Line_Item[' + (currentrowid - 1) + '].Truck_No');
            row.find("td:eq(3) input").attr('name', 'Line_Item[' + (currentrowid - 1) + '].Truck_Trailer');
            row.find("td:eq(3) input").attr('id', 'lineid' + (currentrowid - 1));
            row.find("td:eq(4) input").attr('name', 'Line_Item[' + (currentrowid - 1) + '].Driver_Name');

            row.find("td:eq(5) input").attr('name', 'Line_Item[' + (currentrowid - 1) + '].Licence_No');

            row.find("td:eq(6) input").attr('name', 'Line_Item[' + (currentrowid - 1) + '].Mobile_No');


            row.find("td:eq(7) input").attr('name', 'Line_Item[' + (currentrowid - 1) + '].Product');


            row.find("td:eq(8) input").attr('name', 'Line_Item[' + (currentrowid - 1) + '].Requested_Qty');


            row.find("td:eq(9) input").attr('name', 'Line_Item[' + (currentrowid - 1) + '].Loading_Point');



            row.find("td:eq(10) input").attr('name', 'Line_Item[' + (currentrowid - 1) + '].Destination');



            row.attr('id', currentrowid);
            //  row.find("td:eq(0)").text(currentrowid)

            $('#Table1create tr:last').before(row)
            //   row.appendTo('#Table1');
            return false;


        });



    });





</script>